# Generated by Django 4.0 on 2021-12-09 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sistemagestor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=None)),
                ('estado', models.CharField(choices=[('A', 'ABIERTO'), ('E', 'ENTREGADO'), ('P', 'PENDIENTE'), ('V', 'EN VIAJE')], default='A', max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'db_table': 'appPedidos_pedido',
            },
        ),
        migrations.CreateModel(
            name='ProductoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemagestor.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemagestor.producto')),
            ],
            options={
                'db_table': 'appPedidos_productopedido',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='productosPedidos',
            field=models.ManyToManyField(through='sistemagestor.ProductoPedido', to='sistemagestor.Producto'),
        ),
    ]
